### PR TITLE
Fixing java service example card page (URL links, order, content, etc.)

### LINKED ISSUE #368: Broken link to Mapbox Java Service examples
Path to Mapbox Java Service examples are broken on https://www.mapbox.com/android-docs/mapbox-services/examples/ . Probably because of demo app changes.

### PR DESCRIPTION
**Pull request by langsmith**
This pr fixes #368 (fixing example cards' hyperlinks to demo app examples), improves cards' description text, removes the geocoding example card (removed because the example was removed from the demo app), and adds the matrix card which was missing.

screen shot 2018-03-16 at 5 18 50 pm

### CODE REVIEW

File: src/pages/plugins/examples/index.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /*---
 title: 'Android Plugin Examples'
-description: 'Working code examples of Mapbox's Android Plugins'
+description: 'Working code examples of Mapbox Android Plugins'
```
Comment (cammace) [inline src/pages/plugins/examples/index.js]: This sentence seems a bit off, it should be `Mapbox Plugins for Android`

Comment (langsmith) [reply src/pages/plugins/examples/index.js]: Fixed @cammace
